events {}

http {
    server_tokens off;

    server {
        listen 80;
        server_name ${SERVER_NAME};

        location /.well-known/acme-challenge/ {
            root /var/www/certbot;
        }

        location / {
            return 301 https://$host:37000$request_uri;
        }
    }

    server {
        listen 37000 ssl;
        server_name ${SERVER_NAME};

        ssl_certificate /etc/letsencrypt/live/${SERVER_NAME}/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/${SERVER_NAME}/privkey.pem;
        ssl_protocols TLSv1.2 TLSv1.3;

        location = /v1/chat/completions {
            if ($http_authorization != "Bearer ${LLM_API_KEY}") {
                add_header WWW-Authenticate "Bearer realm=\"llama.cpp\"";
                return 401;
            }

            proxy_pass http://llm:37000;
        }

        location / {
            allow 127.0.0.1;
            allow ::1;
            deny all;

            proxy_pass http://llm:37000;
        }
    }
}
