events {}

http {
    server {
        listen 37000;

        location = /v1/chat/completions {
            proxy_pass http://llm:37000;
        }

        location / {
            allow 127.0.0.1;
            allow ::1;
            deny all;

            proxy_pass http://llm:37000;
        }
    }
}
