events {}

http {
    server_tokens off;

    server {
        listen 80;

        location = /v1/chat/completions {
            if ($http_authorization != "Bearer ${LLM_API_KEY}") {
                add_header WWW-Authenticate "Bearer realm=\"llama.cpp\"";
                return 401;
            }

            proxy_pass http://llm:37000;
        }

        location / {
            return 403;
        }
    }
}
